spring:
  config:
    activate:
      on-profile: dev

### actuator

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: *
    web:
      exposure:
        include: health

  endpoint:
    health:
      enabled: true
      show-components: always

